import mongoose from "mongoose";
import dotenv from "dotenv";
import Event from "./models/Event.js";

dotenv.config();

const events = [
  // HACKATHONS (6)
  { type:"hackathon", title:"HackSphere 2026", organizer:"Google Developer Student Club – KIET", date:"2026-05-10", time:"9:00 AM", duration:"36 hours", mode:"Offline", venue:"Main Auditorium, Block A", prize:"₹1,00,000", tags:["AI/ML","Web Dev","Open Source"], description:"A 36-hour hackathon for building innovative solutions using AI and modern web technologies. Open to all CSE & IT students.", registrationLink:"#", deadline:"2026-05-05", image:"https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600" },
  { type:"hackathon", title:"CodeStorm 7.0", organizer:"IEEE Student Branch – KIET", date:"2026-06-14", time:"10:00 AM", duration:"48 hours", mode:"Online", venue:"Virtual (Devpost Platform)", prize:"₹75,000", tags:["Fintech","Blockchain","Cloud"], description:"Annual flagship hackathon with challenges in Fintech, Blockchain, and Cloud computing. Teams of 2–4 students.", registrationLink:"#", deadline:"2026-06-10", image:"https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600" },
  { type:"hackathon", title:"SmartCity Hackathon 2026", organizer:"ACM Student Chapter – KIET", date:"2026-07-04", time:"8:00 AM", duration:"24 hours", mode:"Hybrid", venue:"Innovation Lab, Block C", prize:"₹50,000", tags:["IoT","Smart Cities","Sustainability"], description:"Build smart sustainable city solutions using IoT and real-time data. Open to all engineering branches.", registrationLink:"#", deadline:"2026-07-01", image:"https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=600" },
  { type:"hackathon", title:"HealthTech Sprint", organizer:"Microsoft Learn Student Ambassadors – KIET", date:"2026-08-22", time:"9:00 AM", duration:"30 hours", mode:"Online", venue:"Virtual (Teams)", prize:"₹60,000", tags:["Healthcare","AI","Azure"], description:"Solve real healthcare challenges using AI, cloud, and wearable data. Mentored by Microsoft engineers.", registrationLink:"#", deadline:"2026-08-18", image:"https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600" },
  { type:"hackathon", title:"AgriCode Challenge", organizer:"Google DSC & CSI KIET", date:"2026-09-15", time:"10:00 AM", duration:"36 hours", mode:"Hybrid", venue:"Central Library Hall", prize:"₹80,000", tags:["AgriTech","ML","Drone Tech"], description:"Create technology-driven solutions for Indian agriculture. Cash prizes plus internship opportunities with AgriTech startups.", registrationLink:"#", deadline:"2026-09-11", image:"https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=600" },
  { type:"hackathon", title:"EduHack 2026", organizer:"KIET EdTech Cell", date:"2026-10-18", time:"9:00 AM", duration:"24 hours", mode:"Offline", venue:"Seminar Hall, Block B", prize:"₹40,000", tags:["EdTech","AR/VR","Gamification"], description:"Reimagine education with immersive technologies. Build apps that make learning engaging and accessible.", registrationLink:"#", deadline:"2026-10-14", image:"https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600" },
  // WORKSHOPS (6)
  { type:"workshop", title:"Full-Stack React & Node.js Bootcamp", organizer:"KIET Web Dev Club", date:"2026-05-20", time:"10:00 AM", duration:"2 days", mode:"Offline", venue:"CS Lab 301, Block A", prize:"", tags:["React","Node.js","MongoDB"], description:"Hands-on 2-day bootcamp covering React hooks, REST APIs, and MongoDB integration. Participants build a full-stack project.", registrationLink:"#", deadline:"2026-05-17", image:"https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600" },
  { type:"workshop", title:"Machine Learning with Python", organizer:"KIET AI/ML Society", date:"2026-06-07", time:"9:30 AM", duration:"1 day", mode:"Hybrid", venue:"Seminar Hall 2 & Live Stream", prize:"", tags:["Python","Scikit-learn","Neural Nets"], description:"Beginner-friendly ML workshop covering supervised learning, model evaluation, and deployment basics using scikit-learn and TensorFlow.", registrationLink:"#", deadline:"2026-06-04", image:"https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600" },
  { type:"workshop", title:"AWS Cloud Practitioner Workshop", organizer:"AWS Educate x KIET", date:"2026-07-12", time:"11:00 AM", duration:"6 hours", mode:"Online", venue:"Virtual (Zoom)", prize:"", tags:["AWS","Cloud","DevOps","S3","EC2"], description:"Get started with AWS services EC2, S3, IAM, Lambda. Prepare for the AWS Cloud Practitioner certification exam.", registrationLink:"#", deadline:"2026-07-10", image:"https://images.unsplash.com/photo-1607706189992-eae578626c86?w=600" },
  { type:"workshop", title:"UI/UX Design Masterclass", organizer:"Figma Community x KIET", date:"2026-08-09", time:"10:00 AM", duration:"1 day", mode:"Offline", venue:"Design Lab, Block D", prize:"", tags:["Figma","UX Research","Prototyping"], description:"Learn the complete design process user research, wireframing, prototyping, and design systems in Figma. Certificate provided.", registrationLink:"#", deadline:"2026-08-06", image:"https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600" },
  { type:"workshop", title:"Cybersecurity & Ethical Hacking", organizer:"Null Chapter – KIET", date:"2026-09-27", time:"9:00 AM", duration:"2 days", mode:"Offline", venue:"Networking Lab, Block E", prize:"", tags:["CTF","Kali Linux","Penetration Testing"], description:"Intensive ethical hacking workshop covering network scanning, web vulnerability exploitation, and CTF challenge walkthroughs.", registrationLink:"#", deadline:"2026-09-24", image:"https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600" },
  { type:"workshop", title:"Docker & Kubernetes for Beginners", organizer:"DevOps Club – KIET", date:"2026-11-08", time:"10:00 AM", duration:"1 day", mode:"Hybrid", venue:"Server Room Lab + Stream", prize:"", tags:["Docker","Kubernetes","CI/CD"], description:"Learn containerisation fundamentals, building Docker images, writing Compose files, and deploying on Kubernetes clusters.", registrationLink:"#", deadline:"2026-11-05", image:"https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600" },
  // PLACEMENT DRIVES (5)
  { type:"placement", title:"TCS NextStep Campus Drive 2026", organizer:"Tata Consultancy Services (TCS)", date:"2026-05-28", time:"8:00 AM", duration:"Full day", mode:"Offline", venue:"Placement Cell, Admin Block", prize:"", tags:["TCS","Software Engineer","CTC 7 LPA"], description:"On-campus placement drive for TCS NextStep. Roles: Software Engineer, Digital Associate. Eligible: 2026 passouts, 60% aggregate.", registrationLink:"#", deadline:"2026-05-22", image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600" },
  { type:"placement", title:"Infosys Power Programmer Drive", organizer:"Infosys Ltd.", date:"2026-07-16", time:"9:00 AM", duration:"Full day", mode:"Online", venue:"HackerEarth Platform", prize:"", tags:["Infosys","Power Programmer","CTC 9.5 LPA"], description:"Infosys Power Programmer Off-Campus drive for 2026 batch. Online test plus technical and HR rounds. CTC up to 9.5 LPA.", registrationLink:"#", deadline:"2026-07-12", image:"https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600" },
  { type:"placement", title:"Wipro Elite National Talent Hunt", organizer:"Wipro Technologies", date:"2026-08-05", time:"9:30 AM", duration:"Full day", mode:"Hybrid", venue:"Exam Hall A + Wipro Office Interview", prize:"", tags:["Wipro","NLTH","CTC 6.5 LPA"], description:"National Talent Hunt for B.Tech 2026 batch. Online aptitude and coding test followed by virtual technical rounds.", registrationLink:"#", deadline:"2026-08-01", image:"https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600" },
  { type:"placement", title:"Accenture ASE & Packaged App Drive", organizer:"Accenture India", date:"2026-09-20", time:"8:30 AM", duration:"Full day", mode:"Offline", venue:"Placement Cell & Interview Rooms", prize:"", tags:["Accenture","ASE","CTC 4.5-8 LPA"], description:"Two roles: Associate Software Engineer 4.5 LPA and Packaged App Developer 8 LPA. Aptitude, coding, and communication assessment.", registrationLink:"#", deadline:"2026-09-15", image:"https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600" },
  { type:"placement", title:"HCL Tech Recruitment 2026", organizer:"HCL Technologies", date:"2026-10-30", time:"9:00 AM", duration:"Full day", mode:"Offline", venue:"KIET Placement Auditorium", prize:"", tags:["HCL","GET","CTC 3.8 LPA"], description:"Graduate Engineer Trainee drive for 2026 batch. Online assessment, group discussion, and HR interview.", registrationLink:"#", deadline:"2026-10-25", image:"https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=600" },
  // SPEAKER SESSIONS (5)
  { type:"speaker", title:"Building at Scale: SDE at Google", organizer:"Google India", date:"2026-05-15", time:"3:00 PM", duration:"2 hours", mode:"Online", venue:"Google Meet (link post-registration)", prize:"", tags:["System Design","SDE","Google Culture"], description:"Google SDE-II Rohan Mehta shares insights on large-scale system design, engineering culture at Google, and how to crack FAANG interviews.", registrationLink:"#", deadline:"2026-05-13", image:"https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=600" },
  { type:"speaker", title:"From Campus to Startup: Founder Journey", organizer:"E-Cell KIET", date:"2026-06-25", time:"4:00 PM", duration:"1.5 hours", mode:"Offline", venue:"Lecture Hall 5, Block B", prize:"", tags:["Entrepreneurship","Startups","Funding"], description:"Priya Sharma, Co-founder of FinEdge (YC W24), talks about building a startup from scratch, raising seed funding, and team building.", registrationLink:"#", deadline:"2026-06-23", image:"https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600" },
  { type:"speaker", title:"AI in Production: Lessons from Industry", organizer:"KIET AI/ML Society", date:"2026-07-30", time:"5:00 PM", duration:"2 hours", mode:"Hybrid", venue:"Seminar Hall 1 + YouTube Live", prize:"", tags:["AI","MLOps","Production ML"], description:"ML engineer from Flipkart discusses AI deployment challenges, A/B testing, monitoring, and real-world ML pipelines.", registrationLink:"#", deadline:"2026-07-28", image:"https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600" },
  { type:"speaker", title:"Open Source: Your Path to Big Tech", organizer:"GitHub Education x KIET", date:"2026-09-05", time:"4:00 PM", duration:"2 hours", mode:"Online", venue:"Virtual (GitHub Meet)", prize:"", tags:["Open Source","GitHub","Community"], description:"GitHub Campus Expert Aditya walks through how open source contributions led to internship offers from CNCF and Mozilla.", registrationLink:"#", deadline:"2026-09-03", image:"https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=600" },
  { type:"speaker", title:"Cracking Product Management Interviews", organizer:"Product Space KIET", date:"2026-11-18", time:"5:00 PM", duration:"2 hours", mode:"Online", venue:"Zoom Webinar", prize:"", tags:["Product Management","PM Interview","Career"], description:"PM at Amazon India shares must-know PM frameworks: STAR method, product design, estimation questions, and metrics.", registrationLink:"#", deadline:"2026-11-16", image:"https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600" },
  // GUEST LECTURES (5)
  { type:"guest_lecture", title:"Ethics in Artificial Intelligence", organizer:"Dr. Priya Nair – IIT Delhi", date:"2026-06-03", time:"11:00 AM", duration:"1.5 hours", mode:"Offline", venue:"Conference Hall, Admin Block", prize:"", tags:["AI Ethics","Bias","Responsible AI"], description:"Prof. Priya Nair discusses fairness, accountability, and transparency in AI systems from algorithmic bias to policy and regulation.", registrationLink:"#", deadline:"2026-06-01", image:"https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600" },
  { type:"guest_lecture", title:"Quantum Computing: Next Frontier", organizer:"Prof. A.K. Sharma – NIT Allahabad", date:"2026-07-22", time:"2:00 PM", duration:"2 hours", mode:"Offline", venue:"Seminar Hall 3, Block A", prize:"", tags:["Quantum","Qubits","Future Tech"], description:"Introduction to quantum computing principles, qubits, quantum gates, and near-term applications in cryptography and optimisation.", registrationLink:"#", deadline:"2026-07-20", image:"https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600" },
  { type:"guest_lecture", title:"Blockchain Beyond Cryptocurrency", organizer:"Dr. Rahul Verma – IIIT Allahabad", date:"2026-08-17", time:"3:00 PM", duration:"1.5 hours", mode:"Hybrid", venue:"LH-7 + Live Stream", prize:"", tags:["Blockchain","Smart Contracts","DeFi"], description:"Explore real-world blockchain use cases in supply chain, identity verification, healthcare records, and decentralised finance.", registrationLink:"#", deadline:"2026-08-15", image:"https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600" },
  { type:"guest_lecture", title:"Data Structures for Competitive Programming", organizer:"Striver (Raj Vikramaditya) – TakeUForward", date:"2026-10-06", time:"4:00 PM", duration:"2.5 hours", mode:"Online", venue:"YouTube Live + Discord Q&A", prize:"", tags:["DSA","Competitive Programming","LeetCode"], description:"Striver covers advanced data structures: segment trees, tries, and sparse tables, with live coding in C++ and Java.", registrationLink:"#", deadline:"2026-10-04", image:"https://images.unsplash.com/photo-1542831371-c5ac92ce3fe8?w=600" },
  { type:"guest_lecture", title:"Industry 5.0 & Future of Engineering", organizer:"Dr. Kavitha Menon – DRDO Scientist", date:"2026-11-25", time:"11:00 AM", duration:"2 hours", mode:"Offline", venue:"Main Auditorium, KIET", prize:"", tags:["Industry 5.0","Robotics","Human-Machine Collaboration"], description:"Senior DRDO scientist discusses emerging technologies shaping Industry 5.0, defence robotics, and career opportunities in national R&D.", registrationLink:"#", deadline:"2026-11-23", image:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600" },
  // COMPETITIONS (5)
  { type:"competition", title:"TechQuiz Championship 2026", organizer:"Quiz Club – KIET", date:"2026-05-25", time:"2:00 PM", duration:"3 hours", mode:"Offline", venue:"Seminar Hall 1", prize:"₹15,000", tags:["Quiz","Technology","CS Fundamentals"], description:"Annual inter-college tech quiz spanning OS, networking, algorithms, data science, and tech trends. Teams of 2.", registrationLink:"#", deadline:"2026-05-22", image:"https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=600" },
  { type:"competition", title:"Robo-Wars Arena 2026", organizer:"Robotics Club – KIET", date:"2026-07-19", time:"9:00 AM", duration:"2 days", mode:"Offline", venue:"Sports Grounds, KIET Campus", prize:"₹30,000", tags:["Robotics","Arduino","Automation"], description:"Build and battle robots in 3 categories: line follower, maze solver, and combat. Open to all engineering colleges in UP.", registrationLink:"#", deadline:"2026-07-14", image:"https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600" },
  { type:"competition", title:"Ideathon – Innovation Unplugged", organizer:"E-Cell x Startup KIET", date:"2026-08-30", time:"10:00 AM", duration:"1 day", mode:"Offline", venue:"Innovation Hub, Block C", prize:"₹25,000 + Incubation Support", tags:["Idea Pitch","Startup","Innovation"], description:"Present your startup idea before a panel of investors and experts. Best ideas get incubation support from KIET TBI.", registrationLink:"#", deadline:"2026-08-26", image:"https://images.unsplash.com/photo-1520366498724-709889c0c685?w=600" },
  { type:"competition", title:"Photography & Videography Contest", organizer:"Media Club – KIET", date:"2026-10-12", time:"10:00 AM", duration:"1 day", mode:"Offline", venue:"Campus-wide (KIET Ghaziabad)", prize:"₹10,000", tags:["Photography","Film","Storytelling"], description:"Theme: Tech & Humanity. Submit photos and short reels captured on campus. Judged on composition, story, and creativity.", registrationLink:"#", deadline:"2026-10-09", image:"https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600" },
  { type:"competition", title:"Case Study Challenge – Deloitte Edition", organizer:"Deloitte x Management Club KIET", date:"2026-11-14", time:"10:00 AM", duration:"1 day", mode:"Hybrid", venue:"Board Room, Admin Block + Virtual", prize:"₹20,000 + PPO Opportunity", tags:["Business","Consulting","Strategy"], description:"Analyse and present a real business case in 15 minutes. Top teams get direct interviews for Deloitte analyst programme.", registrationLink:"#", deadline:"2026-11-10", image:"https://images.unsplash.com/photo-1568992687947-868a62a9f521?w=600" },
  // CODING CONTESTS (6)
  { type:"coding_contest", title:"CodeKIET Monthly: May 2026", organizer:"Competitive Programming Club – KIET", date:"2026-05-31", time:"8:00 PM", duration:"3 hours", mode:"Online", venue:"Codeforces (contest KIET-05)", prize:"₹5,000 + Certificates", tags:["Codeforces","Algorithms","Data Structures"], description:"Monthly rated contest on Codeforces: 6 problems across Div. 2 and Div. 3 difficulty. Open to all KIET students.", registrationLink:"#", deadline:"2026-05-30", image:"https://images.unsplash.com/photo-1542831371-c5ac92ce3fe8?w=600" },
  { type:"coding_contest", title:"HackerEarth Campus Challenge", organizer:"HackerEarth x KIET", date:"2026-06-21", time:"10:00 AM", duration:"2.5 hours", mode:"Online", venue:"HackerEarth Platform", prize:"₹8,000", tags:["HackerEarth","Data Structures","Greedy"], description:"National campus contest on HackerEarth. Problem sets include DP, graphs, and string manipulation. Top KIET rankers win special prizes.", registrationLink:"#", deadline:"2026-06-20", image:"https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600" },
  { type:"coding_contest", title:"LeetCode Weekly – KIET Edition", organizer:"KIET CP Society", date:"2026-07-26", time:"8:00 PM", duration:"1.5 hours", mode:"Online", venue:"LeetCode Platform", prize:"LeetCode Premium Vouchers", tags:["LeetCode","Interview Prep","Weekly"], description:"Weekly contest with 4 graded problems. Top performers earn interview preparation resources and group mentorship sessions.", registrationLink:"#", deadline:"2026-07-26", image:"https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600" },
  { type:"coding_contest", title:"AlgoRush – Intra-College Sprint", organizer:"CSI Chapter KIET", date:"2026-09-11", time:"4:00 PM", duration:"2 hours", mode:"Offline", venue:"CS Lab 302, Block A", prize:"₹6,000", tags:["Graphs","DP","Binary Search"], description:"Intra-college speed coding contest. 5 problems in 2 hours on in-lab systems. Focused on graph algorithms and dynamic programming.", registrationLink:"#", deadline:"2026-09-09", image:"https://images.unsplash.com/photo-1550439062-609e1531270e?w=600" },
  { type:"coding_contest", title:"ICPC Regionals – Practice Contest", organizer:"ICPC Team KIET", date:"2026-10-24", time:"9:00 AM", duration:"5 hours", mode:"Offline", venue:"CS Lab 401, Block A", prize:"ICPC Selection Points", tags:["ICPC","Team Contest","Advanced Algorithms"], description:"Official ICPC-format practice contest for KIET teams. 10 problems, 3-member teams, no internet. Selects KIET teams for regional rounds.", registrationLink:"#", deadline:"2026-10-21", image:"https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=600" },
  { type:"coding_contest", title:"Advent of Code – KIET Group 2026", organizer:"KIET CP Society", date:"2026-12-01", time:"6:00 AM", duration:"25 days", mode:"Online", venue:"adventofcode.com (private leaderboard)", prize:"₹12,000 + Merch", tags:["Advent of Code","Puzzles","Any Language"], description:"Daily coding puzzles throughout December. Solve in any language. KIET private leaderboard with daily prizes for top solvers.", registrationLink:"#", deadline:"2026-11-28", image:"https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600" },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 });
    console.log("Connected to MongoDB");
    await Event.deleteMany({});
    console.log("Cleared existing events");
    const inserted = await Event.insertMany(events);
    console.log(`Seeded ${inserted.length} events successfully`);
    const counts = {};
    inserted.forEach((e) => { counts[e.type] = (counts[e.type] || 0) + 1; });
    console.log("\nBreakdown by type:");
    Object.entries(counts).forEach(([type, count]) => {
      console.log(`  ${type.padEnd(16)} ${count}`);
    });
  } catch (err) {
    console.error("Seed failed:", err.message);
  } finally {
    await mongoose.disconnect();
    console.log("Done.");
  }
}

seed();
